### PR TITLE
Fix translation mistake in 5-SoftMainten

### PR DESCRIPTION
**Pull request by Ethelom**

### CODE REVIEW

**Comment by dspinellis** [comment]
Thank you!  What is the English original?  Also, please consider the translation to the end of the sentence and the correcting ending of "την".

**Comment by Ethelom** [comment]
Below, I cite the English original (Chapter 5, page 107):

_IEEE 14764 classifies adaptive and perfective maintenance  as  maintenance  enhancements._

Could you please explain again your last point? Thank you in advance.

**Comment by dspinellis** [comment]
OK, agreed.  Only please correct into: «**τη** βελτιωτική».  Also I don't like the term «συντήρηση ενισχύσεων», but I can't see a good alternative that doesn't clash with the others.

**Comment by Ethelom** [comment]
I would suggest the following terms:

- συντήρηση εμπλουτισμού

- συντήρηση βελτιστοποίησης

I am not sure, however, if any of the above terms can reflect appropriately the meaning of the term "enhancement".

**Comment by dspinellis** [comment]
Exactly, both are problematic.  Thanks for the fix!

**Pull request merged**
