### PR TITLE
Update Contributors.txt with the new ones

### PR DESCRIPTION
**Pull request by TeoSkondras**

### CODE REVIEW

**Comment by TeoSkondras** [comment]
@dspinellis I will finish it up by tomorrow because maybe some names are not correctly translated!

**Comment by dspinellis** [comment]
OK, ping me when you want me to review it.

**Comment by TeoSkondras** [comment]
@dspinellis I think we are ready. My learn pub account is Theodoros Skondras Mexis (t8200156@aueb.gr)

**Comment by dspinellis** [comment]
I just invited you as an author. Consider using a more permanent email address.  Your full name should appear in Greek.

**Review by dspinellis — APPROVED** [review]
Well done

**Pull request merged**
